appName: k8app
envName: 



deployments:
  - name: k8project
    image:
      repository: nginx
      
    env:
      PORT: "80"
    serviceAccount:
      name: my-service-account
      create: true
      annotations: 
        eks.amazonaws.com/role-arn: arn:aws:iam::128222158613:role/Kesse-project-Cluster-Role
    scale:
      replicas: 1
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3        
        metrics:
          cpu: 50
          memory: 70
    resources:
      requests:
        cpu: 100m
        memory: 50M
      limits:
        cpu: 150m
        memory: 100M
    ports:
      - name: http-frontend
        containerPort: 80
        protocol: TCP        
    
    hooks:
      - command: ["echo", "hi"]
        hook: post-install,pre-upgrade
        name: migrate
    services:
      - name: frontend
        port:
          containerPort: 80
          name: container-access
        


